### ISSUE TITLE
Prebuilt package unavailable

### ISSUE THREAD

**Issue by alexgao1** [jschnasse/oi#14]
The website hosting the prebuilt package is unavailable. (502 Bad Gateway)

**Comment by jschnasse** [comment]
Hi, thank you for your message. Yes, I know - bintray is down for a while. But I hadn't the time to fix the project yet. I hope to put some work into it in the future - but not before September.

You can build the project from source following the steps described at [Clone and Install from Source](https://github.com/jschnasse/oi#clone-and-install-from-source). Don't expect any response/support in the next two weeks, since I'm heavily busy with other things. But thank you for your interest!
